In [200]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [165]:
df=pd.read_csv('global_power_plant.csv')
df

country country_long                          name   gppd_idnr  \
0       IND        India              ACME Solar Tower  WRI1020239   
1       IND        India           ADITYA CEMENT WORKS  WRI1019881   
2       IND        India      AES Saurashtra Windfarms  WRI1026669   
3       IND        India                   AGARTALA GT  IND0000001   
4       IND        India                  AKALTARA TPP  IND0000002   
..      ...          ...                           ...         ...   
902     IND        India                  YERMARUS TPP  IND0000513   
903     IND        India  Yelesandra Solar Power Plant  WRI1026222   
904     IND        India  Yelisirur wind power project  WRI1026776   
905     IND        India                   ZAWAR MINES  WRI1019901   
906     IND        India       iEnergy Theni Wind Farm  WRI1026761   

     capacity_mw  latitude  longitude primary_fuel other_fuel1 other_fuel2  \
0            2.5   28.1839    73.2407        Solar         NaN         NaN   
1           98.0   24.7663    74.6090         Coal         NaN         NaN   
2           39.2   21.9038    69.3732         Wind         NaN         NaN   
3          135.0   23.8712    91.3602          Gas         NaN         NaN   
4         1800.0   21.9603    82.4091         Coal         Oil         NaN   
..           ...       ...        ...          ...         ...         ...   
902       1600.0   16.2949    77.3568         Coal         Oil         NaN   
903          3.0   12.8932    78.1654        Solar         NaN         NaN   
904         25.5   15.2758    75.5811         Wind         NaN         NaN   
905         80.0   24.3500    73.7477         Coal         NaN         NaN   
906         16.5    9.9344    77.4768         Wind         NaN         NaN   

     ...  year_of_capacity_data  generation_gwh_2013 generation_gwh_2014  \
0    ...                    NaN                  NaN                 NaN   
1    ...                    NaN                  NaN                 NaN   
2    ...                    NaN                  NaN                 NaN   
3    ...                 2019.0                  NaN          617.789264   
4    ...                 2019.0                  NaN         3035.550000   
..   ...                    ...                  ...                 ...   
902  ...                 2019.0                  NaN                 NaN   
903  ...                    NaN                  NaN                 NaN   
904  ...                    NaN                  NaN                 NaN   
905  ...                    NaN                  NaN                 NaN   
906  ...                    NaN                  NaN                 NaN   

    generation_gwh_2015 generation_gwh_2016 generation_gwh_2017  \
0                   NaN                 NaN                 NaN   
1                   NaN                 NaN                 NaN   
2                   NaN                 NaN                 NaN   
3            843.747000          886.004428          663.774500   
4           5916.370000         6243.000000         5385.579736   
..                  ...                 ...                 ...   
902            0.994875          233.596650          865.400000   
903                 NaN                 NaN                 NaN   
904                 NaN                 NaN                 NaN   
905                 NaN                 NaN                 NaN   
906                 NaN                 NaN                 NaN   

     generation_gwh_2018  generation_gwh_2019         generation_data_source  \
0                    NaN                  NaN                            NaN   
1                    NaN                  NaN                            NaN   
2                    NaN                  NaN                            NaN   
3             626.239128                  NaN  Central Electricity Authority   
4            7279.000000                  NaN  Central Electricity Authority   
..                   ...    

In [166]:
df.shape

(907, 27)

In [167]:
df.describe()

capacity_mw    latitude   longitude  other_fuel3  commissioning_year  \
count   907.000000  861.000000  861.000000          0.0          527.000000   
mean    326.223755   21.197918   77.464907          NaN         1997.091082   
std     590.085456    6.239612    4.939316          NaN           17.082868   
min       0.000000    8.168900   68.644700          NaN         1927.000000   
25%      16.725000   16.773900   74.256200          NaN         1988.000000   
50%      59.200000   21.780000   76.719500          NaN         2001.000000   
75%     385.250000   25.512400   79.440800          NaN         2012.000000   
max    4760.000000   34.649000   95.408000          NaN         2018.000000   

       wepp_id  year_of_capacity_data  generation_gwh_2013  \
count      0.0                  519.0                  0.0   
mean       NaN                 2019.0                  NaN   
std        NaN                    0.0                  NaN   
min        NaN                 2019.0                  NaN   
25%        NaN                 2019.0                  NaN   
50%        NaN                 2019.0                  NaN   
75%        NaN                 2019.0                  NaN   
max        NaN                 2019.0                  NaN   

       generation_gwh_2014  generation_gwh_2015  generation_gwh_2016  \
count           398.000000           422.000000           434.000000   
mean           2431.823590          2428.226946          2467.936859   
std            4026.440035          4194.596959          4162.884308   
min               0.000000             0.000000             0.000000   
25%             223.557672           176.381063           188.285252   
50%             801.123775           711.181225           737.205450   
75%            3035.306250          3084.121250          3282.861313   
max           28127.000000         30539.000000         30015.000000   

       generation_gwh_2017  generation_gwh_2018  generation_gwh_2019  \
count           440.000000           448.000000                  0.0   
mean           2547.759305          2600.804099                  NaN   
std            4196.991169          4314.880456                  NaN   
min               0.000000             0.000000                  NaN   
25%             177.874930           193.378250                  NaN   
50%             817.977250           751.644375                  NaN   
75%            3275.690475          3143.535900                  NaN   
max           35116.000000         35136.000000                  NaN   

       estimated_generation_gwh  
count                       0.0  
mean                        NaN  
std                         NaN  
min                         NaN  
25%                         NaN  
50%                         NaN  
75%                         NaN  
max                         NaN

In [168]:
df.isnull().sum()

country                       0
country_long                  0
name                          0
gppd_idnr                     0
capacity_mw                   0
latitude                     46
longitude                    46
primary_fuel                  0
other_fuel1                 709
other_fuel2                 906
other_fuel3                 907
commissioning_year          380
owner                       565
source                        0
url                           0
geolocation_source           19
wepp_id                     907
year_of_capacity_data       388
generation_gwh_2013         907
generation_gwh_2014         509
generation_gwh_2015         485
generation_gwh_2016         473
generation_gwh_2017         467
generation_gwh_2018         459
generation_gwh_2019         907
generation_data_source      458
estimated_generation_gwh    907
dtype: int64

In [169]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan, strategy='mean')
df['latitude']=imp.fit_transform(df['latitude'].values.reshape(-1,1))
df['longitude']=imp.fit_transform(df['longitude'].values.reshape(-1,1))
df['commissioning_year']=imp.fit_transform(df['commissioning_year'].values.reshape(-1,1))
df['year_of_capacity_data']=imp.fit_transform(df['year_of_capacity_data'].values.reshape(-1,1))
df['generation_gwh_2014']=imp.fit_transform(df['generation_gwh_2014'].values.reshape(-1,1))
df['generation_gwh_2015']=imp.fit_transform(df['generation_gwh_2015'].values.reshape(-1,1))

In [170]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(strategy='most_frequent')
df['generation_data_source']=imp.fit_transform(df['generation_data_source'].values.reshape(-1,1))
df

country country_long                          name   gppd_idnr  \
0       IND        India              ACME Solar Tower  WRI1020239   
1       IND        India           ADITYA CEMENT WORKS  WRI1019881   
2       IND        India      AES Saurashtra Windfarms  WRI1026669   
3       IND        India                   AGARTALA GT  IND0000001   
4       IND        India                  AKALTARA TPP  IND0000002   
..      ...          ...                           ...         ...   
902     IND        India                  YERMARUS TPP  IND0000513   
903     IND        India  Yelesandra Solar Power Plant  WRI1026222   
904     IND        India  Yelisirur wind power project  WRI1026776   
905     IND        India                   ZAWAR MINES  WRI1019901   
906     IND        India       iEnergy Theni Wind Farm  WRI1026761   

     capacity_mw  latitude  longitude primary_fuel other_fuel1 other_fuel2  \
0            2.5   28.1839    73.2407        Solar         NaN         NaN   
1           98.0   24.7663    74.6090         Coal         NaN         NaN   
2           39.2   21.9038    69.3732         Wind         NaN         NaN   
3          135.0   23.8712    91.3602          Gas         NaN         NaN   
4         1800.0   21.9603    82.4091         Coal         Oil         NaN   
..           ...       ...        ...          ...         ...         ...   
902       1600.0   16.2949    77.3568         Coal         Oil         NaN   
903          3.0   12.8932    78.1654        Solar         NaN         NaN   
904         25.5   15.2758    75.5811         Wind         NaN         NaN   
905         80.0   24.3500    73.7477         Coal         NaN         NaN   
906         16.5    9.9344    77.4768         Wind         NaN         NaN   

     ...  year_of_capacity_data  generation_gwh_2013 generation_gwh_2014  \
0    ...                 2019.0                  NaN         2431.823590   
1    ...                 2019.0                  NaN         2431.823590   
2    ...                 2019.0                  NaN         2431.823590   
3    ...                 2019.0                  NaN          617.789264   
4    ...                 2019.0                  NaN         3035.550000   
..   ...                    ...                  ...                 ...   
902  ...                 2019.0                  NaN         2431.823590   
903  ...                 2019.0                  NaN         2431.823590   
904  ...                 2019.0                  NaN         2431.823590   
905  ...                 2019.0                  NaN         2431.823590   
906  ...                 2019.0                  NaN         2431.823590   

    generation_gwh_2015 generation_gwh_2016 generation_gwh_2017  \
0           2428.226946                 NaN                 NaN   
1           2428.226946                 NaN                 NaN   
2           2428.226946                 NaN                 NaN   
3            843.747000          886.004428          663.774500   
4           5916.370000         6243.000000         5385.579736   
..                  ...                 ...                 ...   
902            0.994875          233.596650          865.400000   
903         2428.226946                 NaN                 NaN   
904         2428.226946                 NaN                 NaN   
905         2428.226946                 NaN                 NaN   
906         2428.226946                 NaN                 NaN   

     generation_gwh_2018  generation_gwh_2019         generation_data_source  \
0                    NaN                  NaN  Central Electricity Authority   
1                    NaN                  NaN  Central Electricity Authority   
2                    NaN                  NaN  Central Electricity Authority   
3             626.239128                  NaN  Central Electricity Authority   
4            7279.000000                  NaN  Central Electricity Authority   
..                   ...    

In [171]:
le=LabelEncoder()
list1=['country', 'country_long', 'name', 'gppd_idnr', 'primary_fuel', 'other_fuel1', 'source', 'url', 'geolocation_source',
      'generation_data_source']
for val in list1:
    df[val]=le.fit_transform(df[val].astype(str))
    
df

country  country_long  name  gppd_idnr  capacity_mw  latitude  longitude  \
0          0             0     0        657          2.5   28.1839    73.2407   
1          0             0     1        519         98.0   24.7663    74.6090   
2          0             0     2        853         39.2   21.9038    69.3732   
3          0             0     3          0        135.0   23.8712    91.3602   
4          0             0     4          1       1800.0   21.9603    82.4091   
..       ...           ...   ...        ...          ...       ...        ...   
902        0             0   902        491       1600.0   16.2949    77.3568   
903        0             0   903        822          3.0   12.8932    78.1654   
904        0             0   904        891         25.5   15.2758    75.5811   
905        0             0   905        539         80.0   24.3500    73.7477   
906        0             0   906        876         16.5    9.9344    77.4768   

     primary_fuel  other_fuel1 other_fuel2  ...  year_of_capacity_data  \
0               6            3         NaN  ...                 2019.0   
1               1            3         NaN  ...                 2019.0   
2               7            3         NaN  ...                 2019.0   
3               2            3         NaN  ...                 2019.0   
4               1            2         NaN  ...                 2019.0   
..            ...          ...         ...  ...                    ...   
902             1            2         NaN  ...                 2019.0   
903             6            3         NaN  ...                 2019.0   
904             7            3         NaN  ...                 2019.0   
905             1            3         NaN  ...                 2019.0   
906             7            3         NaN  ...                 2019.0   

     generation_gwh_2013 generation_gwh_2014  generation_gwh_2015  \
0                    NaN         2431.823590          2428.226946   
1                    NaN         2431.823590          2428.226946   
2                    NaN         2431.823590          2428.226946   
3                    NaN          617.789264           843.747000   
4                    NaN         3035.550000          5916.370000   
..                   ...                 ...                  ...   
902                  NaN         2431.823590             0.994875   
903                  NaN         2431.823590          2428.226946   
904                  NaN         2431.823590          2428.226946   
905                  NaN         2431.823590          2428.226946   
906                  NaN         2431.823590          2428.226946   

     generation_gwh_2016  generation_gwh_2017  generation_gwh_2018  \
0                    NaN                  NaN                  NaN   
1                    NaN                  NaN                  NaN   
2                    NaN                  NaN                  NaN   
3             886.004428           663.774500           626.239128   
4            6243.000000          5385.579736          7279.000000   
..                   ...                  ...                  ...   
902           233.596650           865.400000           686.500000   
903                  NaN                  NaN                  NaN   
904                  NaN                  NaN                  NaN   
905                  NaN                  NaN                  NaN   
906                  NaN                  NaN                  NaN   

     generation_gwh_2019  generation_data_source  estimated_generation_gwh  
0                    NaN                       0                       NaN  
1                    NaN                       0                       NaN  
2                    NaN                       0                       NaN  
3                    NaN                       0                       NaN  
4                    NaN                       0                       NaN  
..         

In [172]:
df['primary_fuel'].value_counts()

1    258
3    251
6    127
7    123
2     69
0     50
5     20
4      9
Name: primary_fuel, dtype: int64

In [173]:
X=df.drop(columns=['capacity_mw', 'other_fuel2', 'other_fuel2', 'other_fuel3', 'owner', 'wepp_id', 'generation_gwh_2013',
                   'generation_gwh_2016', 'generation_gwh_2017','generation_gwh_2018', 'generation_gwh_2019', 
                   'estimated_generation_gwh'], axis=1)
Y=df['capacity_mw']

In [174]:
print(X)
print(Y)

     country  country_long  name  gppd_idnr  latitude  longitude  \
0          0             0     0        657   28.1839    73.2407   
1          0             0     1        519   24.7663    74.6090   
2          0             0     2        853   21.9038    69.3732   
3          0             0     3          0   23.8712    91.3602   
4          0             0     4          1   21.9603    82.4091   
..       ...           ...   ...        ...       ...        ...   
902        0             0   902        491   16.2949    77.3568   
903        0             0   903        822   12.8932    78.1654   
904        0             0   904        891   15.2758    75.5811   
905        0             0   905        539   24.3500    73.7477   
906        0             0   906        876    9.9344    77.4768   

     primary_fuel  other_fuel1  commissioning_year  source  url  \
0               6            3         2011.000000     109  128   
1               1            3         1997.09108

In [175]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.33,random_state=47)

In [176]:
X_train

country  country_long  name  gppd_idnr   latitude  longitude  \
475        0             0   475        253  11.801400  77.808500   
518        0             0   518        614  20.927600  79.245500   
133        0             0   133         67  22.393200  82.553200   
329        0             0   329        495  21.197918  77.464907   
433        0             0   433        228  17.860800  81.681400   
..       ...           ...   ...        ...        ...        ...   
584        0             0   584        313  18.681400  73.494800   
264        0             0   264        680  21.302700  74.309100   
327        0             0   327        173  22.389000  82.554900   
902        0             0   902        491  16.294900  77.356800   
135        0             0   135         69  32.596600  75.985700   

     primary_fuel  other_fuel1  commissioning_year  source  url  \
475             3            3         1960.000000      22   58   
518             1            3         1997.091082     171  168   
133             1            2         2010.000000      22   58   
329             3            3         2016.000000      22   58   
433             3            3         1976.000000      22   58   
..            ...          ...                 ...     ...  ...   
584             3            3         1988.000000      22   58   
264             7            3         1997.091082      21  208   
327             1            2         2011.000000      22   58   
902             1            2         2016.000000      22   58   
135             3            3         1994.000000      22   58   

     geolocation_source  year_of_capacity_data  generation_gwh_2014  \
475                   2                 2019.0            440.40690   
518                   2                 2019.0           2431.82359   
133                   2                 2019.0            373.91900   
329                   2                 2019.0           2431.82359   
433                   2                 2019.0           1280.67445   
..                  ...                    ...                  ...   
584                   2                 2019.0           2431.82359   
264                   2                 2019.0           2431.82359   
327                   2                 2019.0           1564.16300   
902                   2                 2019.0           2431.82359   
135                   2                 2019.0           2539.04100   

     generation_gwh_2015  generation_data_source  
475           339.722850                       0  
518          2428.226946                       0  
133           417.168000                       0  
329          2428.226946                       0  
433          1226.974300                       0  
..                   ...                     ...  
584          2428.226946                       0  
264          2428.226946                       0  
327          1683.597000                       0  
902             0.994875                       0  
135          2610.581500                       0  

[607 rows x 16 columns]

In [177]:
Y_train

475     250.0
518      65.0
133      60.0
329     195.0
433     460.0
        ...  
584      10.0
264      25.5
327     270.0
902    1600.0
135     540.0
Name: capacity_mw, Length: 607, dtype: float64

In [178]:
lm=LinearRegression()

In [179]:
lm.fit(X_train,Y_train)

LinearRegression()

In [180]:
lm.score(X_train,Y_train)

0.7537133160068928

In [181]:
lm.coef_

array([ 0.00000000e+00,  1.46688217e-12,  2.96657163e-01, -6.36313242e-01,
       -9.95993884e-01, -2.81354295e+00, -6.59245945e+00, -2.67453337e+02,
        5.74095706e+00, -1.14870136e+00,  3.43933767e-02, -2.88618698e+01,
       -2.84217094e-14,  1.54520241e-02,  1.15506003e-01,  0.00000000e+00])

In [182]:
from sklearn.linear_model import Lasso,Ridge

In [183]:
ls=Lasso(alpha=0.0001)
ls.fit(X_train,Y_train)
ls.score(X_train,Y_train)

0.7537133160065002

In [184]:
ls.coef_

array([ 0.00000000e+00,  0.00000000e+00,  2.96657170e-01, -6.36313268e-01,
       -9.95986382e-01, -2.81353226e+00, -6.59235061e+00, -2.67452597e+02,
        5.74096592e+00, -1.14869775e+00,  3.43901000e-02, -2.88613262e+01,
        0.00000000e+00,  1.54520482e-02,  1.15506020e-01,  0.00000000e+00])

In [185]:
rd=Ridge(alpha=0.0001)
rd.fit(X_train,Y_train)

Ridge(alpha=0.0001)

In [186]:
rd.coef_

array([ 0.00000000e+00,  0.00000000e+00,  2.96657257e-01, -6.36313390e-01,
       -9.95994018e-01, -2.81353936e+00, -6.59249763e+00, -2.67452881e+02,
        5.74096109e+00, -1.14870248e+00,  3.43939025e-02, -2.88619324e+01,
        0.00000000e+00,  1.54520351e-02,  1.15506008e-01,  0.00000000e+00])

In [187]:
from sklearn.linear_model import ElasticNet
enr=ElasticNet(alpha=0.0001)
enr.fit(X_train,Y_train)
enrpred=enr.predict(X_test)
print(enr.score(X_train,Y_train))
enr.coef_

0.7537133109099855


array([ 0.00000000e+00,  0.00000000e+00,  2.96685652e-01, -6.36358076e-01,
       -9.96030885e-01, -2.81245013e+00, -6.60398503e+00, -2.67314577e+02,
        5.74218550e+00, -1.14903934e+00,  3.45511697e-02, -2.88805527e+01,
        0.00000000e+00,  1.54553695e-02,  1.15507684e-01,  0.00000000e+00])

In [201]:
from sklearn.svm import SVR
 
svr = SVR(kernel = 'linear')
svr.fit(X_train,Y_train)
svr.score(X_train,Y_train)
pred_Y=svr.predict(X_test)

svr = SVR(kernel = 'poly')
svr.fit(X_train,Y_train)
svr.score(X_train,Y_train)
pred_Y=svr.predict(X_test)

svr = SVR(kernel = 'rbf')
svr.fit(X_train,Y_train)
svr.score(X_train,Y_train)
pred_Y=svr.predict(X_test)


In [202]:
from sklearn.svm import SVR

kernellist=['linear', 'poly', 'rbf']
for i in kernellist:
    sv=SVR(kernel=i)
    sv.fit(X_train,Y_train)
    print(svr.score(X_train,Y_train))

-0.1707785110628457
-0.1707785110628457
-0.1707785110628457


In [205]:
X=df.drop(columns=['capacity_mw', 'other_fuel2', 'other_fuel2', 'other_fuel3', 'owner', 'wepp_id', 'generation_gwh_2013',
                   'generation_gwh_2016', 'generation_gwh_2017','generation_gwh_2018', 'generation_gwh_2019', 
                   'estimated_generation_gwh'], axis=1)
Y=df['primary_fuel']

In [206]:
print(X)
print(Y)

     country  country_long  name  gppd_idnr  latitude  longitude  \
0          0             0     0        657   28.1839    73.2407   
1          0             0     1        519   24.7663    74.6090   
2          0             0     2        853   21.9038    69.3732   
3          0             0     3          0   23.8712    91.3602   
4          0             0     4          1   21.9603    82.4091   
..       ...           ...   ...        ...       ...        ...   
902        0             0   902        491   16.2949    77.3568   
903        0             0   903        822   12.8932    78.1654   
904        0             0   904        891   15.2758    75.5811   
905        0             0   905        539   24.3500    73.7477   
906        0             0   906        876    9.9344    77.4768   

     primary_fuel  other_fuel1  commissioning_year  source  url  \
0               6            3         2011.000000     109  128   
1               1            3         1997.09108

In [207]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.33,random_state=47)

In [208]:
X_train.shape

(607, 16)

In [209]:
Y_train.shape

(607,)

In [210]:
lm.score(X_train,Y_train)

-71359.03374966042

In [211]:
lm.coef_

array([ 0.00000000e+00,  1.46688217e-12,  2.96657163e-01, -6.36313242e-01,
       -9.95993884e-01, -2.81354295e+00, -6.59245945e+00, -2.67453337e+02,
        5.74095706e+00, -1.14870136e+00,  3.43933767e-02, -2.88618698e+01,
       -2.84217094e-14,  1.54520241e-02,  1.15506003e-01,  0.00000000e+00])

In [212]:
ls=Lasso(alpha=0.0001)
ls.fit(X_train,Y_train)
ls.score(X_train,Y_train)

0.9999999718228249

In [213]:
ls.coef_

array([ 0.00000000e+00,  0.00000000e+00,  8.76774901e-07, -1.67237678e-06,
       -0.00000000e+00,  1.04867987e-07,  1.00002000e+00,  0.00000000e+00,
        7.97949294e-07,  3.06709259e-06,  2.92657289e-06, -0.00000000e+00,
        0.00000000e+00, -2.91449589e-07,  2.54613422e-07,  0.00000000e+00])

In [214]:
rd=Ridge(alpha=0.0001)
rd.fit(X_train,Y_train)

Ridge(alpha=0.0001)

In [215]:
rd.coef_

array([ 0.00000000e+00,  0.00000000e+00, -3.31676234e-12,  1.90107887e-10,
        9.38989496e-10, -2.08930296e-10,  9.99999874e-01,  1.69601559e-07,
       -1.02735033e-09, -2.78876496e-09,  2.05638246e-09, -2.19971907e-07,
        0.00000000e+00, -1.92952623e-12, -2.32647204e-12,  0.00000000e+00])

In [216]:
#from sklearn.linear_model import ElasticNet
enr=ElasticNet(alpha=0.0001)
enr.fit(X_train,Y_train)
enrpred=enr.predict(X_test)
print(enr.score(X_train,Y_train))
enr.coef_

0.9999999680170205


array([ 0.00000000e+00,  0.00000000e+00,  9.50210613e-07, -2.00985789e-06,
       -2.50114503e-06,  4.85256586e-06,  1.00005788e+00,  0.00000000e+00,
        2.00180927e-06,  4.07792869e-06,  2.89484062e-06, -2.35818183e-05,
        0.00000000e+00, -2.86114583e-07,  2.53867552e-07,  0.00000000e+00])

In [217]:
from sklearn.svm import SVR
 
svr = SVR(kernel = 'linear')
svr.fit(X_train,Y_train)
svr.score(X_train,Y_train)
pred_Y=svr.predict(X_test)

svr = SVR(kernel = 'poly')
svr.fit(X_train,Y_train)
svr.score(X_train,Y_train)
pred_Y=svr.predict(X_test)

svr = SVR(kernel = 'rbf')
svr.fit(X_train,Y_train)
svr.score(X_train,Y_train)
pred_Y=svr.predict(X_test)

In [218]:
from sklearn.svm import SVR

kernellist=['linear', 'poly', 'rbf']
for i in kernellist:
    sv=SVR(kernel=i)
    sv.fit(X_train,Y_train)
    print(svr.score(X_train,Y_train))

0.3444914232334382
0.3444914232334382
0.3444914232334382
